apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocdupdate
  name: argocdupdate
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: argocdupdate
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: argocdupdate
    spec:
      containers:
      - name: argocdupdate
        image: ghcr.io/nginxinc/nginx-unprivileged:1.27.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
          limits:
            memory: 84Mi
            cpu: 100m
        securityContext:
          runAsUser: 101
          runAsGroup: 101
          allowPrivilegeEscalation: false
      terminationGracePeriodSeconds: 15
