apiVersion: v1
kind: Service
metadata:
  labels:
    app: argoupdate
  name: argoupdate
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: argoupdate
